source 'https://rubygems.org'
ruby File.read(File.dirname(__FILE__)+'/.ruby-version').strip

gem 'async-io' # -> gem 'console'
gem 'json'
gem 'rest-client'
gem 'falcon'

gem 'sinatra', '>=4.0.0'
gem 'sinatra-reloader'
gem 'slim'

gem 'rack', '>=3.0.0'
gem 'rackup'
gem 'rack-cors'
gem 'rack-sassc'

gem 'jwt'
gem 'ed25519'

gem 'stack-service-base'
#, path: '/home/user/projects/stack-service-base'

group :development do
  gem 'rubocop'
end
